obstacle_range: 2.5
raytrace_range: 3.0

# Box robot
# footprint: [[0.85, -0.4], [0.85, 0.4], [-0.15, 0.4], [-0.15, -0.4]]

footprint: [[1.400, -1.0], [1.400, 1], [-1.400, 1.0], [-1.400, -1]]

publish_frequency: 1.0

obstacle_layer:
  observation_sources: scan3d
  scan3d:
    data_type: PointCloud2
    topic: front_3d_lidar/points
    marking: true
    clearing: true
    inf_is_valid: false
    min_obstacle_height: 0.3

